version: '3'

include:
  - ./proxy.yaml

services:
  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: always
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_HOST="%"
    volumes:
      - ./my.cnf:/etc/my.cnf
    #  - ./db_virtd:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      backend: 
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile.python
    image: python_web
    container_name: python_web
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=172.20.0.10
      - DB_USER=${MYSQL_USER}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
    
    networks:
      backend: 
        ipv4_address: 172.20.0.5
